[build]
command = "python functions/app.py"
publish = "dolanjo"

[context.production.environment]
PYTHON_VERSION = "3.8"

[context.production]
command = "python functions/app.py"
publish = "dolanjo"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
