[build]
command = "python functions/app.py"
publish = "/"

[context.production.environment]
PYTHON_VERSION = "3.8"

[context.production]
command = "python functions/app.py"
publish = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
