[build]
command = " pip install -r requirements.txt && python -m gunicorn -b 0.0.0.0:$PORT functions.app:app"
publish = "dolanjo"

[context.production.environment]
PYTHON_VERSION = "3.8"

[context.production]
command = "pip install -r requirements.txt && python -m gunicorn -b 0.0.0.0:$PORT functions.app:app"
publish = "dolanjo"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
